import os

env = Environment()

env['CXX'] = 'g++'

# # lib_var = os.popen("root-config --libs").read()

env['CCFLAGS'] = '-DLINUXVERS -g -Wall -DWITH_DEBUG' 

output = os.environ["ROOTSYS"]

root_sys = os.environ["ROOTSYS"] 
root_sys_inc = root_sys + "/include"

env.Append(CPPPATH =[root_sys_inc, root_sys])

root_lib = os.popen("root-config --libs").read()

env['LIBS'] = 'nsl', 'crypt', 'dl', 'Minuit', 'Xt', 'X11', 'Xpm' 

env.ParseConfig('/home/apps/root/bin/root-config --libs')

#env.ParseConfig('/usr/bin/root-config --libs')

env.Program(target = "eic", source = ["main.cc", "eic.cc", "eic_pim.cc", "tssa_sig_Para.cc"])


